In [8]:
import re
import os
import sys
import csv

import numpy as np



In [9]:
a = np.arange(60).reshape(3,4,5)

print(a)

a = np.delete(a, 1, 0)

print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [10]:
a = np.ones((3, 4, 500, 500))

print(a[:, 1].shape)

(3, 500, 500)


In [11]:
a = np.arange(20)
b = np.arange(10,30)

b[a > 15]


array([26, 27, 28, 29])

In [12]:
ok_img_list = ['a.png', 'b.png']
ng_img_list = ['c.png', 'd.png']
ok_dir = './debug_ok'
ng_dir = './debug_ng'

ok_fname_list = []
for i in img_list:
    ok_fname = test_dir +'/'+ i
#     print(ok_fname)
    ok_fname_list.append(ok_fname)
    
print(img_list)
print(test_dir)
print(ok_fname_list)


['a.png', 'b.png']
./debug
['./debug/a.png', './debug/b.png']


In [17]:
a = np.arange(20).reshape(4,5)
b = np.tile(a, 3)

b


array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])