In [4]:
import os
import sys
import csv
import numpy as np

In [5]:
root = 'I:/ykato_git/datasets/omg_instance_segmentation/dataset_ver4/dataset_arrange/spline'

fname = root + '/age1000location4_0000.csv'

with open(fname, 'r') as f:
    reader = csv.reader(f)
    
    for row in reader:
        print(list(map(int,row)))

[0, 0, 324, 250]
[0, 1, 324, 251]
[0, 2, 324, 253]
[0, 3, 325, 255]
[0, 4, 324, 257]
[0, 5, 324, 259]
[0, 6, 323, 260]
[0, 7, 324, 262]
[1, 0, 200, 268]
[1, 1, 212, 268]
[1, 2, 217, 268]
[1, 3, 234, 262]
[1, 4, 243, 258]
[1, 5, 250, 254]
[1, 6, 259, 250]
[1, 7, 266, 246]
[2, 0, 320, 269]
[2, 1, 320, 267]
[2, 2, 321, 264]
[2, 3, 322, 261]
[2, 4, 322, 259]
[2, 5, 323, 256]
[2, 6, 324, 253]
[2, 7, 324, 250]
[3, 0, 316, 263]
[3, 1, 310, 264]
[3, 2, 303, 266]
[3, 3, 295, 268]
[3, 4, 288, 269]
[3, 5, 281, 271]
[3, 6, 271, 274]
[3, 7, 263, 276]
[4, 0, 283, 325]
[4, 1, 286, 319]
[4, 2, 293, 316]
[4, 3, 297, 307]
[4, 4, 300, 301]
[4, 5, 306, 294]
[4, 6, 311, 288]
[4, 7, 314, 283]
[5, 0, 308, 262]
[5, 1, 307, 260]
[5, 2, 306, 260]
[5, 3, 309, 263]
[5, 4, 309, 263]
[5, 5, 309, 263]
[5, 6, 286, 260]
[5, 7, 285, 260]
[6, 0, 281, 323]
[6, 1, 282, 316]
[6, 2, 285, 311]
[6, 3, 290, 304]
[6, 4, 295, 299]
[6, 5, 299, 293]
[6, 6, 303, 289]
[6, 7, 310, 287]
[7, 0, 298, 268]
[7, 1, 300, 267]
[7, 2, 303, 26

In [7]:
a = np.arange(48)
a = a.reshape((3, 8, 2))

print(a)

a[:,:,1] = 50 - a[:,:,1]

print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]
  [30 31]]

 [[32 33]
  [34 35]
  [36 37]
  [38 39]
  [40 41]
  [42 43]
  [44 45]
  [46 47]]]
[[[ 0 49]
  [ 2 47]
  [ 4 45]
  [ 6 43]
  [ 8 41]
  [10 39]
  [12 37]
  [14 35]]

 [[16 33]
  [18 31]
  [20 29]
  [22 27]
  [24 25]
  [26 23]
  [28 21]
  [30 19]]

 [[32 17]
  [34 15]
  [36 13]
  [38 11]
  [40  9]
  [42  7]
  [44  5]
  [46  3]]]


In [25]:
print(a.shape)
b = a
# print(b)
c = np.concatenate(b, axis=0)
print(c.shape)
d=np.concatenate(b, axis=1)
print(d.shape)

(3, 8, 2)
(24, 2)
(8, 6)
